const express = require('express')
const verify = require('./Verify')
const { GetUSer, UpdateUserPicture, GetImage, ChangeInfo, NewPassword, Register, Login, Logout } = require('./Controler')
const refresh = require('./RefreshToken')
const { GetAllPosts, AddPost, UpdatePost, PostView, LikeCounter, DeletePost, GetMyPost } = require('./Post/PostControler')
const Upload = require('./Upload')
const Reset = require('./ResetPassword/ResetPassword')
const { CreateComment } = require('./Comment/CommentControler')
const router = express.Router()


router.get('/users', GetUSer, verify)
router.get('/GetUsers', GetUSer)
router.post('/user', Register)
router.post('/Login', Login)
router.get('/token', refresh)
router.delete('/Logout', Logout)
router.get('/posts', GetAllPosts)
router.post('/addPost', AddPost, Upload)
router.get('/GetMyPost', GetMyPost)
router.put('/Update', UpdatePost)
router.get('/Post/:id', PostView)
router.post("/upload", UpdateUserPicture, Upload)
router.get('/GetIMG', GetImage)
router.delete('/deletePost', DeletePost)
router.put('/ChangeInfo', ChangeInfo)
router.post('/Reset', Reset)
router.post('/Post/:id', CreateComment)
router.post("/LikePost/:id", LikeCounter)
router.post("/NewPass", NewPassword)
module.exports = router